version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
    restart: always


  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb

  leaky-bucket-graphql-relay: 
    image: rp83t1/leaky-bucket-graphql-relay:latest
    hostname: leaky-bucket-graphql-relay
    ports:
     - "4000:4000"    
    depends_on:
      - mongodb
    restart: always

volumes:
  mongo-data:
    driver: local

networks:
  default:
    driver: bridge
    name: network